version: "3.7"

# volumes list.
volumes:
  mysql-data:        # Persist MySQL data.

# services definition.
services:
  app: # Application container
    build:
      context: docker
      dockerfile: App.Dockerfile
    container_name: lilbank_app
    volumes:
      - .:/var/www/app
      # - /etc/letsencrypt/live/lilbank.com.br/privkey.pem:/home/ambientum/certs/privkey.pem
      # - /etc/letsencrypt/live/lilbank.com.br/fullchain.pem:/home/ambientum/certs/fullchain.pem

    ports:
      - 80:8080
      - 443:8443
    restart: always

  db:  # MySQL database
    container_name: lilbank_db
    build:
      context: docker
      dockerfile: Db.Dockerfile
    volumes:
      - 'mysql-data:/var/lib/mysql' # persist "/var/lib/mysql" on volume "mysql-data".
    environment:
      - MYSQL_ROOT_PASSWORD=lilbank  # password for user user root.
      - MYSQL_DATABASE=lilbank       # database name (to be created on first run).
      - MYSQL_USER=lilbank           # regular user name.
      - MYSQL_PASSWORD=lilbank       # regular user password.
    restart: always

  assets: # Application container
    image: ambientum/node:13
    container_name: lilbank_assets
    volumes:
      - .:/var/www/app
    command: npm run prod